project_name: omadasitedns
before:
  hooks:
    - sh -c "cd ./src && go get github.com/ramr/go-reaper"
    - sh -c "cd ./src && go mod tidy"
    - sh -c "cd ./src && go mod download"
builds:
  - dir: src
    binary: omadasitedns
    env:
      - CGO_ENABLED=0
      - CXX=g++
      - GOGCCFLAGS=-fPIC -marm -fmessage-length=0
      - CC=gcc
#    ldflags:
#      - -linkmode external -extldflags -static
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/kwitsch/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/kwitsch/{{ .ProjectName }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/kwitsch/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "ghcr.io/kwitsch/{{ .ProjectName }}:latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 6
    image_templates:
      - "ghcr.io/kwitsch/{{ .ProjectName }}:{{ .Version }}-armv6"
      - "ghcr.io/kwitsch/{{ .ProjectName }}:latest-armv6"
    build_flag_templates:
      - "--platform=linux/arm/v6"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    image_templates:
      - "ghcr.io/kwitsch/{{ .ProjectName }}:{{ .Version }}-armv7"
      - "ghcr.io/kwitsch/{{ .ProjectName }}:latest-armv7"
    build_flag_templates:
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: ghcr.io/kwitsch/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/kwitsch/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/kwitsch/{{ .ProjectName }}:{{ .Version }}-arm64v8
      - ghcr.io/kwitsch/{{ .ProjectName }}:{{ .Version }}-armv6
      - ghcr.io/kwitsch/{{ .ProjectName }}:{{ .Version }}-armv7
  - name_template: ghcr.io/kwitsch/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/kwitsch/{{ .ProjectName }}:latest-amd64
      - ghcr.io/kwitsch/{{ .ProjectName }}:latest-arm64v8
      - ghcr.io/kwitsch/{{ .ProjectName }}:latest-armv6
      - ghcr.io/kwitsch/{{ .ProjectName }}:latest-armv7
