name: Build Edge

on:
  push:
    branches: 
      - development

jobs:
  goreleaser:
    name: GoReleaser
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout ⬇
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Golang ⚙
        uses: actions/setup-go@v3
        with:
          go-version: ~1.17

      - name: Setup Golang caches ⚙
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-golang-
      
      - name: Setup QEMU ⚙
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      
      - name: Setup Docker Buildx ⚙
        uses: docker/setup-buildx-action@v1
      
      - name: Setup Docker layer cache ⚙
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Registry 🔒
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run GoReleaser 💨
        uses: goreleaser/goreleaser-action@v3
        if: ${{ success() }}
        with:
          version: latest
          args: release --rm-dist -f .goreleaser/edge.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

      - name: Sanetize repo string ⚙
        id: string
        if: ${{ success() }}
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}

      - name: Push edge images ⬆
        if: ${{ success() }}
        run: |
          docker push ghcr.io/${{ steps.string.outputs.lowercase }}:edge-amd64
          docker push ghcr.io/${{ steps.string.outputs.lowercase }}:edge-arm64v8
          docker push ghcr.io/${{ steps.string.outputs.lowercase }}:edge-armv6
          docker push ghcr.io/${{ steps.string.outputs.lowercase }}:edge-armv7

          docker manifest create \
          ghcr.io/${{ steps.string.outputs.lowercase }}:edge \
          --amend ghcr.io/${{ steps.string.outputs.lowercase }}:edge-amd64 \
          --amend ghcr.io/${{ steps.string.outputs.lowercase }}:edge-arm64v8 \
          --amend ghcr.io/${{ steps.string.outputs.lowercase }}:edge-armv6 \
          --amend ghcr.io/${{ steps.string.outputs.lowercase }}:edge-armv7

          docker manifest push ghcr.io/${{ steps.string.outputs.lowercase }}:edge

      - name: Clean Docker cache 🧹
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache