name: Build Development

on:
  push:
    branches: 
      - development
  workflow_dispatch:

jobs:
  goreleaser:
    name: GoReleaser
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout ⬇
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Golang ⚙
        uses: actions/setup-go@v3
        with:
          go-version: ~1.17

      - name: Setup QEMU ⚙
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      
      - name: Setup Docker Buildx ⚙
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Registry 🔒
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run GoReleaser 💨
        uses: goreleaser/goreleaser-action@v3
        if: ${{ success() }}
        with:
          version: latest
          args: release --rm-dist -f .goreleaser/dev.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

      - name: Sanetize repo string ⚙
        id: string
        if: ${{ success() }}
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}

      - name: Push dev images ⬆
        if: ${{ success() }}
        run: |
          docker push ghcr.io/${{ steps.string.outputs.lowercase }}:dev-amd64
          docker push ghcr.io/${{ steps.string.outputs.lowercase }}:dev-arm64v8
          docker push ghcr.io/${{ steps.string.outputs.lowercase }}:dev-armv6
          docker push ghcr.io/${{ steps.string.outputs.lowercase }}:dev-armv7

          docker manifest create \
          ghcr.io/${{ steps.string.outputs.lowercase }}:dev \
          --amend ghcr.io/${{ steps.string.outputs.lowercase }}:dev-amd64 \
          --amend ghcr.io/${{ steps.string.outputs.lowercase }}:dev-arm64v8 \
          --amend ghcr.io/${{ steps.string.outputs.lowercase }}:dev-armv6 \
          --amend ghcr.io/${{ steps.string.outputs.lowercase }}:dev-armv7

          docker manifest push ghcr.io/${{ steps.string.outputs.lowercase }}:dev